#! /bin/sh
fcitx5 &

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh
feh --bg-scale ~/Pictures/wallpaper.jpg
nohup syncthing@Echo.service &> /dev/null &
nm-applet &
udiskie &
# synergyc 192.168.31.171 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^3'
bspc rule -a Inkscape desktop='^2'
bspc rule -a Zathura state=tilled
bspc rule -a Libreoffice desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
xsetroot -cursor_name left_ptr
